### ISSUE TITLE
Redundant Room dependence

### ISSUE THREAD

**Issue by thuypt** [kodeba/surveys-android#12]
<img width="848" alt="screen shot 2560-12-27 at 12 14 39" src="https://user-images.githubusercontent.com/6264092/34371424-93aed5a0-eaff-11e7-9896-9f05ebed7e8b.png">
`Room` was added as a dependency, but did you use it in the project?

**Comment by kodeba** [comment]
At first I plan to do offline data but the time runout 
and I forgot to remove it

for now it removed

**Comment by thuypt** [comment]
@kodeba Could you add a reference the fixed commit to here?
(your commit or pull request that fixed this issue)
It will be easier to check and follow your solutions. Same with others issue.

**Comment by kodeba** [comment]
sure
this issue fixed on this commit 320d738deefc9b4c7b355385d81764d259bc51ef
