### ISSUE TITLE
Request for testing

### ISSUE THREAD

**Issue by sleepylee** [kodeba/surveys-android#2]
As testing is an essential part of development, could we request to have testing initiated for this project as well? Ideally, to save time, let's make a few of it but the ones you think that do matters the most, both unit testing and ui testing (optional, but valuable).

**Comment by kodeba** [comment]
I already implement unit testing on data layer, basically when I'm do testing 
I'll setup API in my laptop and test with local data 

for UI testing, honestly I didn't found solution for test ViewModel (Architecture Component) yet
Normally when I'm do UI testing with async task like send request to API
I'll use Idling Resource to handle it

Please help check it again thank you
